### ISSUE TITLE
Some feedback

### ISSUE THREAD

**Issue by n0nag0n** [myaghobi/f3-migrations#1]
Hi there! We meet again :)

Looking over this, I think 2 things would be very beneficial.

1. If this were able to be installed with composer. Placing it in the `lib/` folder is outdated and pretty manual :'(
1a. Since this is installed with composer you could specify you need the `f3-schema` plugin to be installed.
2. If you could specify where you wanted your db migrations to be in, instead of the `lib/db/migrations`

Otherwise this is a great looking plugin and something I've kinda been looking to using in an upcoming project I've wanted to do. So thank you!

**Comment by ikkez** [comment]
This is a very nice idea. Definitely useful. However I also have some feedback:

- The actions `Refresh`, `Fresh` and `Reset` are all more or less the same for my taste. It could happen very quickly that you type the wrong thing and don't know what just happend. One "Reset" to reset all migrations is fine. When you want to want to migrate afterwards again, just run another command.

- Also I think a simple "rollback" action is missing, which just rollbacks the very last migration only.
- The actions should also be usable via console (cli) only. So Hardcoding html in the returns isn't that great
- The code uses the Session. Why? I think it should not use the session at all.
- MigrationsModel  and MigrationCase  should have their own file


thanks for you work!

**Comment by n0nag0n** [comment]
@ikkez Thanks for going in much deeper. I was just glazing the surface! Each class should be it's own file even though Fat-Free doesn't obey that rule.

**Comment by myaaghubi** [comment]
@ikkez, @n0nag0n thank you both for feedback.
@ikkez,
- I tried to make the actions work like `Laravel Migrations`. Therefore it will familiar to developers. Any difference could be unpleasant.
- For the classes, `MigrationsModel` and `MigrationCase`, I have checked some plugins and tried to follow the procedures of other plugins, just like the `f3-schema-builder`.
- The web interface is simple in usage, it may need to add some confirmation dialog. Also, the `CLI` is a great idea and please feel free to make PR.

@n0nag0n, note that using `composer` is great and I'll use it to host this plugin too, but what about the manual installation!? I think Fat-Free needs a better structure for plugins, to make a plugin with multiple classes or even non-PHP resources, otherwise, putting multiple classes just for one plugin in `lib/`!? it's not a good idea.

I know this plugin can have more features, note that this is the first stable release and it's in progress.

**Comment by n0nag0n** [comment]
You can have both methods so someone can pick. I personally wouldn't use the manual install method cause all my projects are done through composer. But if someone had a legacy fat free app, it might make sense that way.

You could (and should) namespace your plugin. That way you won't have collisions with other classes no matter what you name em. If I remember right, I think you can just dump a certain folder if you have multiple classes in the `lib/` dir and it will scan the whole folder... @ikkez can correct me if I'm wrong.

**Comment by myaaghubi** [comment]
I made a new release, please check out that. 
Just two points to mention:
- That performance issue, I think, is a bug in the `Mapper` class and not related to this plugin. After the first insert with `Mapper`, it goes 60-80 times slower.
- For `CLI` mode, first, going to make another f3-plugin(in my next free time) to help plugins to work in `CLI` mode.

**Comment by n0nag0n** [comment]
I peaked over your commits and they look good. What performance issue are you referring to?

**Comment by myaaghubi** [comment]
I noticed the issue as mentioned in the feedback of  @ikkez,
